services:
  baikal:
    image: ghcr.io/duquemh41/baikal:latest
    container_name: baikal
    ports:
      - "8080:80"
    volumes:
      - ./config:/var/www/baikal/config
      - ./data:/var/www/baikal/Specific
    restart: unless-stopped
